const std = @import("std");
const builtin = @import("builtin");
const InputStream = @import("stream.zig").InputStream;
const tokenize = @import("lexer.zig").tokenize;
const parse = @import("parser.zig").parse;
const create_global_table = @import("tables.zig").create_global_table;
const type_checking = @import("analysis.zig").type_checking;
const generate_code_x86 = @import("generator.zig").generate_code;
const saveAndCompileAssembly_x86 = @import("generator.zig").saveAndCompileAssembly;
const Types = @import("lexer.zig").Types;

const stdlib_source = @embedFile("stdlib.aio");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    std.debug.print("Building Stdlib\n", .{});

    var stream = InputStream.init(stdlib_source);
    // defer stream.deinit(allocator);

    var token_list = try tokenize(allocator, &stream);
    defer token_list.deinit(allocator);
    // token_list.head.?.print();

    const ast = try parse(allocator, &token_list);
    defer ast.destroy(allocator);

    // ast.print(0);

    // Select backend based on architecture
    const symbol_table = try create_global_table(allocator, ast);
    defer symbol_table.deinit(allocator);
    try symbol_table.calculate_offsets();
    try type_checking(symbol_table, ast);

    // symbol_table.print_tables();
    const assembly = try generate_code_x86(allocator, ast, symbol_table, true);
    defer allocator.free(assembly);

    const generated_file = try std.fs.cwd().createFile("src/stdlib_x86_64_generated.s", .{});
    defer generated_file.close();
    try generated_file.writeAll(assembly);

    const as_result = try std.process.Child.run(.{ .allocator = allocator, .argv = &[_][]const u8{
        "as",
        "src/stdlib_x86_64_generated.s",
        "-o",
        "src/stdlib_x86_64_generated.o",
    } });
    std.debug.print("{s}", .{as_result.stdout});
    std.debug.print("{s}", .{as_result.stderr});
    // Generate function signature table as Zig code
    var zig_code = try std.ArrayList(u8).initCapacity(allocator, 256);
    defer zig_code.deinit(allocator);

    try zig_code.appendSlice(allocator,
        \\// Auto-generated by build_stdlib.zig - DO NOT EDIT
        \\const Types = @import("lexer.zig").Types;
        \\
        \\pub const FunctionSignature = struct {
        \\    name: []const u8,
        \\    return_type: Types,
        \\    parameters: []const Parameter,
        \\    in_use: bool,
        \\};
        \\
        \\pub const Parameter = struct {
        \\    name: []const u8,
        \\    type: Types,
        \\};
        \\
        \\// Use optimized version if available, otherwise use generated
        \\pub const stdlib_assembly_x86_64 = @embedFile("stdlib_x86_64_generated.o");
        \\
        \\pub const functions = [_]FunctionSignature{
        \\
    );

    // Generate function signatures from AST
    for (ast.program.items) |func_node| {
        if (func_node.* == .function_def) {
            const func = func_node.function_def;

            var buffer: [1024]u8 = undefined;

            const func_start = try std.fmt.bufPrint(&buffer, "    .{{\n", .{});
            try zig_code.appendSlice(allocator, func_start);

            const name_line = try std.fmt.bufPrint(&buffer, "        .name = \"{s}\",\n", .{func.name});
            try zig_code.appendSlice(allocator, name_line);

            const return_line = try std.fmt.bufPrint(&buffer, "        .return_type = Types.{s},\n", .{typeToZigString(func.return_type)});
            try zig_code.appendSlice(allocator, return_line);

            try zig_code.appendSlice(allocator, "        .parameters = &[_]Parameter{\n");

            for (func.parameters.items) |param| {
                const p = param.function_parameter;
                const param_line = try std.fmt.bufPrint(&buffer, "            .{{ .name = \"{s}\", .type = Types.{s} }},\n", .{
                    p.name,
                    typeToZigString(p.type),
                });
                try zig_code.appendSlice(allocator, param_line);
            }

            try zig_code.appendSlice(allocator, "        },\n");
            try zig_code.appendSlice(allocator, "        .in_use = false,\n");
            try zig_code.appendSlice(allocator, "    },\n");
        }
    }

    try zig_code.appendSlice(allocator, "};\n");

    // Write Zig code
    const zig_file = try std.fs.cwd().createFile("src/stdlib_generated.zig", .{});
    defer zig_file.close();
    try zig_file.writeAll(zig_code.items);
}
fn typeToZigString(_type: Types) []const u8 {
    return switch (_type) {
        .void => "Void",
        .bool => "Bool",
        .char => "Char",
        .int => "Int",
        .word => "Word",
        .char_array => |size| {
            // For now, just use Char as a fallback
            // You could extend this to handle arrays properly
            _ = size;
            return "Char";
        },
    };
}
