// Auto-generated by build_stdlib.zig - DO NOT EDIT
const Types = @import("lexer.zig").Types;

pub const FunctionSignature = struct {
    name: []const u8,
    return_type: Types,
    parameters: []const Parameter,
    in_use: bool,
};

pub const Parameter = struct {
    name: []const u8,
    type: Types,
};

// Use optimized version if available, otherwise use generated
pub const stdlib_assembly_x86_64 = @embedFile("stdlib_x86_64_generated.o");

pub const functions = [_]FunctionSignature{
    .{
        .name = "exit",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "err_code", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "open",
        .return_type = Types.Int,
        .parameters = &[_]Parameter{
            .{ .name = "file_name", .type = Types.Word },
            .{ .name = "flags", .type = Types.Int },
            .{ .name = "mode", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "close",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "file_descriptor", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "write",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "fd", .type = Types.Int },
            .{ .name = "buf", .type = Types.Word },
            .{ .name = "count", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "byte_out",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "out", .type = Types.Char },
        },
        .in_use = false,
    },
    .{
        .name = "byte_in",
        .return_type = Types.Char,
        .parameters = &[_]Parameter{
        },
        .in_use = false,
    },
    .{
        .name = "print",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "num", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "read",
        .return_type = Types.Word,
        .parameters = &[_]Parameter{
            .{ .name = "fd", .type = Types.Int },
            .{ .name = "buf", .type = Types.Word },
            .{ .name = "count", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "read_line",
        .return_type = Types.Int,
        .parameters = &[_]Parameter{
            .{ .name = "buffer", .type = Types.Word },
            .{ .name = "max_len", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "mmap",
        .return_type = Types.Word,
        .parameters = &[_]Parameter{
            .{ .name = "addr", .type = Types.Word },
            .{ .name = "length", .type = Types.Word },
            .{ .name = "prot", .type = Types.Int },
            .{ .name = "flags", .type = Types.Int },
            .{ .name = "fd", .type = Types.Int },
            .{ .name = "offset", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "munmap",
        .return_type = Types.Word,
        .parameters = &[_]Parameter{
            .{ .name = "addr", .type = Types.Word },
            .{ .name = "length", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "memcpy",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "dest", .type = Types.Word },
            .{ .name = "src", .type = Types.Word },
            .{ .name = "n", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "memset",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "dest", .type = Types.Word },
            .{ .name = "value", .type = Types.Char },
            .{ .name = "n", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "memeql",
        .return_type = Types.Bool,
        .parameters = &[_]Parameter{
            .{ .name = "a", .type = Types.Word },
            .{ .name = "b", .type = Types.Word },
            .{ .name = "n", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "strlen",
        .return_type = Types.Int,
        .parameters = &[_]Parameter{
            .{ .name = "s", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "strcmp",
        .return_type = Types.Int,
        .parameters = &[_]Parameter{
            .{ .name = "sa", .type = Types.Word },
            .{ .name = "sb", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "strcpy",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "dest", .type = Types.Word },
            .{ .name = "src", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "print_string",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "str", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "print_int",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "n", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "print_hex",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "n", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "is_digit",
        .return_type = Types.Bool,
        .parameters = &[_]Parameter{
            .{ .name = "c", .type = Types.Char },
        },
        .in_use = false,
    },
    .{
        .name = "exp",
        .return_type = Types.Int,
        .parameters = &[_]Parameter{
            .{ .name = "base", .type = Types.Int },
            .{ .name = "power", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "ascii_to_integer",
        .return_type = Types.Int,
        .parameters = &[_]Parameter{
            .{ .name = "str", .type = Types.Word },
        },
        .in_use = false,
    },
    .{
        .name = "integer_to_ascii",
        .return_type = Types.Word,
        .parameters = &[_]Parameter{
            .{ .name = "n", .type = Types.Int },
            .{ .name = "buffer", .type = Types.Word },
            .{ .name = "base", .type = Types.Int },
        },
        .in_use = false,
    },
    .{
        .name = "reverse",
        .return_type = Types.Void,
        .parameters = &[_]Parameter{
            .{ .name = "buff", .type = Types.Word },
            .{ .name = "count", .type = Types.Int },
        },
        .in_use = false,
    },
};
